[package]
name = "rstgrep"
version = "0.2.0"
authors = ["Sameh Abouelsaad <samehabouelsaad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
anyhow = "1.0"
regex = "1"